Cubed-Development/Modern-Warfare-Cubed

- src/main/java/com/paneedah/weaponlib/CommonModContext.java
For sake of imporving user experience.
> Add weapon workbench and ammo press to block creativetabs

- src/main/resources/assets/mwc/lang/en_US.lang
> Fixed EN_US.lang having mwc Instead of MWC

- src/main/java/com/paneedah/mwc/creativetab/PropsTab.java
- src/main/java/com/paneedah/mwc/wearables/Bullets.java
Yes, I know you guys are removing props, but until then, it should be a different icon. 
Lowered the 40mm stack size from 64 to 16 so it's less overpowered.
> Change Props tab icon + Lower 40mm stack size

- src/main/java/com/paneedah/mwc/skins/CustomSkin.java
- src/main/java/com/paneedah/mwc/skins/GunSkins.java
- src/main/java/com/paneedah/weaponlib/AttachmentBuilder.java
- src/main/java/com/paneedah/weaponlib/ItemSkin.java
- src/main/java/com/paneedah/weaponlib/WeaponRenderer.java
- src/main/java/com/paneedah/weaponlib/compatibility/CompatibleStaticModelSourceRenderer.java
Unfortunately has to be a janky implementation due to `Minecraft.getMinecraft()` being null during pre-init, which, Dynamic Resources require the Minecraft instance.
Note: Servers will also need the images in order to register.
> Added support for custom skins. Tested with 0 performance impacts.

- src/main/resources/assets/mwc/recipes/carbon_composite.json
- src/main/resources/assets/mwc/recipes/flash_grenade.json
- src/main/resources/assets/mwc/recipes/impact_grenade.json
- src/main/resources/assets/mwc/recipes/m67_grenade.json
- src/main/resources/assets/mwc/recipes/smoke_grenade.json
These can be tweaked later, but these are good to have.
> Grenade crafting recipes  

- src/main/java/com/paneedah/mwc/wearables/Bullets.java
- src/main/java/com/paneedah/mwc/wearables/Vests.java
> Give Vests Durability 

- Changelog.md
- src/main/java/com/paneedah/mwc/items/guns/PythonFactory.java
- src/main/java/com/paneedah/mwc/items/guns/TaurusRagingHunterFactory.java
- src/main/java/com/paneedah/weaponlib/CustomGui.java
- src/main/java/com/paneedah/weaponlib/config/ModernConfigManager.java
Ability to configure the position, size, and reversal of the bullet counter
> Configurable bullet counter

- src/main/java/com/paneedah/weaponlib/ClientEventHandler.java
Making sure it's up-to-date with Equipment-Overhaul.
> Fix Desoro failing to merge

- Changelog.md
- src/main/java/com/paneedah/mwc/items/guns/M17Factory.java
- src/main/java/com/paneedah/mwc/items/guns/M249Factory.java
- src/main/java/com/paneedah/mwc/items/guns/P90Factory.java
Fixed most of the visual bugs on the M249, M17 RMR and Slide view has recoil and the P90 Terminator Converter magazine can now be loaded
https://github.com/Cubed-Development/Modern-Warfare-Cubed/assets/133471454/858f9d49-bea8-4717-995e-6b6cbc984f5a
Note: there are visual bugs in many things but they are things that I cannot fix without so much knowledge
> Fixed M249, M17 Slide and P90 Terminator Mag

- Changelog.md
- src/main/java/com/paneedah/mwc/tileentities/TileEntities.java
Removes broken/unusable props and updates bounding boxes for:
- Single Floodlight
- Shelf Top
- Server Rack Top
Props are going to be completely changed, but until then I will fix their hitboxes
Do not break any props (I'm fixing the dumpster next pr)
1.12.2
N/A
N/A
> More Prop Fixes + Delete Broken Props

- Changelog.md
- src/main/java/com/paneedah/mwc/tileentities/TileEntities.java
Fixes more hitboxes
See other PR's
1.12.2
> More Prop Fixes (Fixes the Dumpster)

- Changelog.md
- src/main/java/com/paneedah/mwc/tileentities/TileEntities.java
Fixes the hitboxes for 
- Hanging Body
- Office Chair
- Office Chair 2
- Home Chair
- White Desk Middle
See other pr's
Fix the props
1.12.2
N/a
N/A
> Even more prop fixes

- Changelog.md
- src/main/java/com/paneedah/mwc/tileentities/TileEntities.java
Fixed Medical Create, Camera Rotated, and tweaked hitbox of Shelf Top 
See other PRs
adjust prop hitboxes
1.12.2
N/A
N/A
> 90% of props are fixed.

- src/main/resources/assets/mwc/lang/en_US.lang
Adds lang stuff to the keys that are missing  
Makes it easier to edit keybinding
Dont break it 
1.12.2
> Add missing lang info to en_US

- Changelog.md
- src/main/java/com/paneedah/weaponlib/config/ModernConfigManager.java
Changes the description of some configs and makes it so by default, terrorists do not spawn  
Everyone turns off the spawning for terrorists, this will save people time
Dont break the config
1.12.2
N/A
N/A
> Config Changes 

- Changelog.md
Changes some spelling/grammar and removes the 
- Expanded crafting to accommodate any type of planks
change I made that had to be reverted by Stick. 
Grammarly was getting too mad whenever i was editing this file. 
Keep info easily readable. 
N/A
1.12.2
N/A
N/A
> Petty changes to Changelog.md

- Changelog.md
- src/main/java/com/paneedah/mwc/items/guns/BrowningAuto5Factory.java
Shotgun now ejects shells after firing, like it does[ in real life ](https://www.youtube.com/watch?v=YHPQ1vrHMJs)
Consistency with the real world 
Not break the gun
1.12.2
N/A
N/A
> Make Browning Auto 5 eject shotgun shell

- src/main/java/com/paneedah/mwc/tileentities/TileEntities.java
Sandbag prop's hotbox is a little too big, keeps eating bullets  
Hardness was too high (But can be changed now)
Sandbag kept eating bullets
Propane tank was a slightly too tall 
Not break the props 
1.12.2
N/A
N/A
> More Hitbox Adjustments + Hardness Adjust 

- src/main/resources/assets/mwc/lang/en_US.lang
Fixes the spelling mistake i made and adds the rest of the Vehicle keybinds 
Lets users have a easier time changing configs
Fix keybindings
Yes, it works
1.12.2
N/A
N/A
> Fix Vehicle Lang

- src/main/java/com/paneedah/mwc/tileentities/TileEntities.java
Fixes conflict with master as a result of #270
@Koud-Wind 
Fix conflict
#270 
N/A
> Fix Conflict With #270
